version: "3"

networks:
    web-network:
        driver: ${NETWORKS_DRIVER}

services:
### Nginx ###########################################
    nginx:
        image: nginx:${NGINX_VERSION}
        container_name: xhgui_nginx
        ports:
            - "${NGINX_PORT}:80"
        restart: always
        networks:
            - web-network
        volumes:
            - ${WWW_ROOT_LOCAL}:${WWW_ROOT_CONTAINER}
            - ./docker/nginx/conf:/etc/nginx/conf.d
        working_dir: ${WWW_ROOT_CONTAINER}
        depends_on:
            - php
### PHP-FPM ###########################################
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                - PHP_VERSION=${PHP_VERSION}
                - TZ=${TZ}
        container_name: xhgui_php
        restart: always
        networks:
            - web-network
        volumes:
            - ${WWW_ROOT_LOCAL}:${WWW_ROOT_CONTAINER}
            - ${DATA_DIR}/cache:${WWW_ROOT_CONTAINER}/cache
            - ${DATA_DIR}/logs/php:/var/log/php-fpm
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: ${WWW_ROOT_CONTAINER}
        ports:
            - "${PHP_FPM_PORT}:9000"
        environment:
            - XHGUI_ENV=docker
        depends_on:
            - mongodb
### mongodb ###########################################
    mongodb:
        build:
            context: ./docker/mongo
            args:
                - MONGO_VERSION=${MONGO_VERSION}
        container_name: xhgui_mongodb
        restart: always
        ports:
            - "${MONGO_PORT}:27017"
        volumes:
            - ${DATA_DIR}/mongo:/data/db
        networks:
            - web-network
### Receiver ###########################################
    receiver:
        image: light/swoole:1.0.0
        container_name: xhgui_receiver
        ports:
            - "${UDP_REV_PORT}:9501"
        restart: always 
        networks:
            - web-network
        volumes:
            - ${WWW_ROOT_LOCAL}:${WWW_ROOT_CONTAINER}
            - ${DATA_DIR}/cache:${WWW_ROOT_CONTAINER}/cache
        working_dir: ${WWW_ROOT_CONTAINER}
        command: php swoole.php 
